// Generated by https://quicktype.io

export interface DependecyResponse {
  name:    string;
  hidden:  boolean;
  content: Content[];
}

export interface Content {
  id:           string;
  name:         string;
  description:  string;
  ginniCommon:  boolean;
  group:        string;
  hidden:       boolean;
  versionRange: null | string;
  versionRequired: null | string;
}

export interface IDependency extends DependecyResponse {};